Generate Typescript documentation from wit files
NomicFoundation/slang pull request #1157
Opened 2024-11-22 22:32 UTC by mjoerussell

This PR uses the `jco types` command to generate Typescript definitions for the wasm crates instead of `jco transpile`. The reason is that `jco transpile` generates ts definitions by decoding WASM component binaries, whereas `jco types` parses .wit files directly and uses that information. This means that the `Resolve` instance created during `types` has access to the type documentation info, and the one created during `transpile` does not.

I've modified `infra check npm` with a new step which calls `jco types` and handles the resulting .d.ts files. When calling `jco transpile` we're now passing the option `--no-typescript` to avoid generating conflicting typescript outputs.

These changes depend on https://github.com/NomicFoundation/jco/pull/1, which augments the `types` command to accept the same configuration file that we pass to `transpile`. Without this, the codegen in `types` will not be able to generate Typescript enums for Rust enums, or any other customization that we want.

2024-11-22 22:33 UTC, mjoerussell commented
The core changes are done, but I still need to debug an issue with the npm tests. After these changes Jest is not able to resolve the module imports, even though `infra check` still succeeds. I'll keep looking and see if there's a deeper issue.

2024-11-26 12:18 UTC, OmarTawfik commented on Cargo.toml
> +wasm-tools = { version = "1.202.0" }
is this downgrade intended? not sure I understand the reason.
Also, nit blank lines.

2024-11-26 12:24 UTC, OmarTawfik commented on Cargo.toml
>  [workspace.lints.rust]
for `submodules/jco`, I suggest updating it to: https://github.com/NomicFoundation/jco/commit/a951a946df8a2e4a9db3d12d210b925a93d7ccae

2024-11-26 12:27 UTC, OmarTawfik commented on crates/infra/cli/src/toolchains/wasm/mod.rs
> +                .flag("--no-typescript") // disable generating .d.ts files - we'll do this in `generate_types` with a better generator
nit: outdated comment?

```suggestion
                .flag("--no-typescript") // disable generating .d.ts files - we'll do this in `jco types` below
```

2024-11-26 12:28 UTC, OmarTawfik commented on crates/infra/cli/src/toolchains/wasm/mod.rs
>                  "js" => {
nit: left over?

2024-11-26 12:31 UTC, OmarTawfik commented on crates/codegen/runtime/npm/package/wasm/generated/interfaces/nomic-foundation-slang-parser.d.ts
>  export class ParseError {
I don't see the type-level documentation for many classes, like `ParseError` and `ParseOutput`. Am I missing something?

2024-11-26 12:41 UTC, OmarTawfik commented on crates/codegen/runtime/npm/package/wasm/generated/interfaces/nomic-foundation-slang-cst.d.ts
>    isTerminalNode(): false;
seems like these are also missing doc comments. But maybe that is more related to #1166 and can be done in a separate PR.

2024-11-26 12:44 UTC, OmarTawfik requested changes
Left a few questions.

2024-11-28 10:52 UTC, OmarTawfik commented on crates/codegen/runtime/npm/package/wasm/generated/interfaces/nomic-foundation-slang-parser.d.ts
>  export class ParseError {
Sounds good. We can do that in #1171

2024-11-28 10:57 UTC, OmarTawfik approved these changes
I think there is still [one remaining issue](https://github.com/NomicFoundation/slang/pull/1157#discussion_r1861960929), but otherwise, LGTM.

2024-12-02 20:04 UTC, merged