Allow defining built-ins types and functions only inside relevant contexts
NomicFoundation/slang pull request #1203
Opened 2024-12-24 17:20 UTC by ggiraldez

The changes in this PR would allow us to remove all Yul keywords defined for built-ins and declare them as built-ins, to be bound only in assembly statements context. This would simplify the language grammar.

2025-02-07 21:31 UTC, OmarTawfik commented on crates/codegen/language/definition/src/model/built_ins.rs
> +    pub name: String,
nit: for consistency with the rest of the model.

```suggestion
    pub name: Identifier,
```

2025-02-07 21:36 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
> +                BuiltInVariable(definition = "$Function $placeholder"),
not sure I understand `$Function $placeholder` here. How is this used?

2025-02-07 21:37 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/bindings.rs
> +        if context.name == "$YulBuiltIns$" {
That means that *ALL* Solidity built-ins are accessible from Yul. Right?

2025-02-07 21:48 UTC, OmarTawfik commented on crates/solidity/inputs/language/bindings/rules.msgb
> +    ; NOTE: since we're no longer ingesting built-ins from an external Solidity
> how to link to a fixed, built-in scope

what would be a use case for that?

If none, since both the public API and the bindings internal code are now using "built-ins", should we rename "system files" to "built-in files" to avoid confusion?

2025-02-07 21:48 UTC, ggiraldez commented on crates/solidity/inputs/language/src/definition.rs
> +                BuiltInVariable(definition = "$Function $placeholder"),
This is used to bind the `_` placeholder in function modifiers [here](https://github.com/manastech/slang/blob/built-in-contexts/crates/solidity/inputs/language/bindings/rules.msgb#L1618-L1623). But... I think we could get away with defining it as `BuiltInVariable(definition = "$Function _")` and avoid the "translation". We couldn't before because we needed to parse a Solidity file with this definition.

And come to think of it, we can now replace all `$` in built-ins definitions directly with `%`.

2025-02-07 21:50 UTC, ggiraldez commented on crates/solidity/inputs/language/src/bindings.rs
> +        if context.name == "$YulBuiltIns$" {
No, not quite. Because reference nodes created from Yul identifiers are still guarded by a `@yul` symbol before they can reach the built-ins scope.

2025-02-07 21:53 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
>                          Keyword(
Removing these yul keywords means they are no longer reserved, which can lead us to parse the following incorrectly as an identifier, and produce no errors. Is that a regression?

```
let not := 0
```

2025-02-07 21:54 UTC, ggiraldez commented on crates/solidity/inputs/language/bindings/rules.msgb
> +    ; NOTE: since we're no longer ingesting built-ins from an external Solidity
That's a good point. I don't think we'll need `add_system_file` that in the public API either. I can't think of any reason why we would need it. And then we can remove the code in the rules and graph builder functions to deal with that as well.

2025-02-07 22:03 UTC, ggiraldez commented on crates/solidity/inputs/language/src/definition.rs
>                          Keyword(
Oh... I didn't realize, but yes, I think it's a regression. That means we cannot change the grammar as we intended, right? But we'll instead need to add binding rules for all reserved keywords, to generate binding references from them.

2025-02-07 22:06 UTC, ggiraldez commented on crates/solidity/inputs/language/src/definition.rs
>                          Keyword(
Or can we parse them as `YulIdentifier` in the context of a function call, while still reserving them as keywords?

2025-02-07 22:07 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
>                          Keyword(
Not sure if a bigger change is needed, since we are not doing validation.
I would be more concerned about cases where we produce incorrect trees for valid code, which is a simpler problem to solve.
Let's talk about it on Monday before we do a bigger change here.

2025-02-07 22:08 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
>                          Keyword(
Thinking about it, I'm more concerned about cases where we produce incorrect trees for valid code, which is a simpler problem to solve.

Let's talk about it on Monday before we do a bigger change here, since we are not doing validation.

2025-02-14 22:46 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
>      binding_rules_file = "crates/solidity/inputs/language/bindings/rules.msgb",
I suggest adding a `minor` changeset for the change to use contexts in bindings, and a `patch` changeset for the #1244 fix.

2025-02-14 22:50 UTC, OmarTawfik commented on crates/solidity/testing/snapshots/cst_output/YulVariableAssignmentStatement/identifier_add/input.sol
> -add := 0
I suggest keeping a couple of these tests as a regression test:

```sol
// this identifier is unreserved, and parsed as a built-in function. See #1203:
add := 0
```

2025-02-14 22:50 UTC, OmarTawfik commented on crates/solidity/testing/snapshots/cst_output/YulFunctionCallExpression/built_in_and/input.sol
> -and()
I suggest keeping a couple of these tests as a regression test:

```sol
// this identifier is unreserved, and bound as a built-in function. See #1203:
and()
```

2025-02-14 22:55 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/bindings.rs
> +        if context.name == "$YulBuiltIns$" {
Do we have tests that cover these cases?

- that we don't bind a Solidity built-in in a Yul context.
- that we don't bind a Yul built-in in a Solidity context.

2025-02-14 22:56 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
> -                            name = YulAbstractKeyword,
Not sure I understand why was `YulAbstractKeyword` removed here?

2025-02-14 23:01 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
> -                            name = YulAbstractKeyword,
If unintended, I suggest doing a quick `println!()`/diff to make sure that the added and removed entries here are the same.

2025-02-14 23:08 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
> +                BuiltInVariable(definition = "%Function _"),
IIUC, `_` is a valid function name in Solidity, and users can invoke it normally.

How do we make sure we bind it only within modifiers? do we have a test for that?

2025-02-14 23:11 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
> +                BuiltInVariable(definition = "%Function _"),
nit suggestion: adding a comment to explain this:

```suggestion
                // Placeholder for modifiers, to be used to inject the original modified function (`_;`)
                BuiltInVariable(definition = "%Function _"),
```

2025-02-14 23:13 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
> +                BuiltInVariable(definition = "%Function _"),
IIUC, `_` is a valid function name in Solidity, and users can invoke it normally.
The below code compiles successfully:

```solidity
contract Foo {
    function _() public {}

    function bar() public {
        _; // refers to the function above
    }
}
```

How do we make sure we bind it only within modifiers? do we have a test for that?

2025-02-14 23:27 UTC, OmarTawfik requested changes
Left a few qestions.

2025-02-15 07:28 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
> +                ),
IIUC, `_` is a valid function name in Solidity, and users can invoke it normally.
The below code compiles successfully:

```solidity
contract Foo {
    function _() public {}

    function bar() public {
        _; // refers to the function above
    }
}
```

How do we make sure we bind it only within modifiers? do we have a test for that?

2025-02-15 07:29 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
> +                BuiltInVariable(definition = "$Function $placeholder"),
Thanks for explaining. I suggest adding a comment to explain this:

```rs
                // Placeholder for modifiers, to be used to inject the modified function body (`_;`)
                BuiltInVariable(definition = "%Function _"),
```

2025-02-16 22:04 UTC, ggiraldez commented on crates/solidity/inputs/language/src/definition.rs
> -                            name = YulAbstractKeyword,
Hmm... this was definitely unintended. I'll restore it and check that there are no more similar cases.

2025-02-16 22:31 UTC, ggiraldez commented on crates/solidity/inputs/language/src/definition.rs
> -                            name = YulAbstractKeyword,
I couldn't find any other cases of unintended removals. All other removed Yul keywords are added as built-in functions.

2025-02-17 02:09 UTC, ggiraldez commented on crates/solidity/inputs/language/src/bindings.rs
> +        if context.name == "$YulBuiltIns$" {
Added tests for both cases. Solidity built-ins *were* being bound in Yul contexts, so I updated the binding rules to fix that.

2025-02-19 03:54 UTC, OmarTawfik commented on crates/solidity/testing/snapshots/bindings_output/yul/solidity_built_in_doesn_t_bind/input.sol
> +        }
nit suggestion:

```suggestion
        ripemd160(); // binds correctly (Solidity context)
        assembly {
            ripemd160() // doesn't bind (Yul context)
        }
```

2025-02-19 03:55 UTC, OmarTawfik commented on crates/solidity/testing/snapshots/bindings_output/built_ins/yul_built_in_doesn_t_bind/input.sol
> +        mstore();
nit suggestion:

```suggestion
        mstore(); // doesn't bind (Solidity context)

        assembly {
            mstore(); // binds correctly (Yul context)
        }
```

2025-02-19 03:58 UTC, OmarTawfik commented on crates/solidity/testing/snapshots/cst_output/YulVariableAssignmentStatement/identifier_and/input.sol
> +// this identifier is unreserved, and bound as a built-in function. See #1203:
updating the comment here:

```suggestion
// this identifier is unreserved, and bound as a variable name. See #1203:
```

2025-02-19 04:05 UTC, OmarTawfik commented on crates/solidity/testing/snapshots/bindings_output/yul/external_variables/generated/0.5.8-failure.txt
> + 8 │             c := d.slot
I think this is a bug? because of the change in `YulIdentifier` grammar. `slot` is not bound here.

2025-02-19 04:06 UTC, OmarTawfik requested changes
Did another round, and resolved earlier comments.

2025-02-19 14:53 UTC, ggiraldez commented on crates/solidity/testing/snapshots/bindings_output/yul/external_variables/generated/0.5.8-failure.txt
> + 8 │             c := d.slot
No, this is expected. `YulIdentifier`s may contain dots specifically from 0.5.8 until 0.7.0. So in this case, `d.slot` is being parsed as a single identifier, not a path.

Before 0.7.0, the syntax to access the slot of a storage variable was to use the `_slot` suffix, eg. `d_slot` in this case.

2025-02-20 04:38 UTC, OmarTawfik commented on crates/solidity/testing/snapshots/bindings_output/yul/external_variables/generated/0.5.8-failure.txt
> + 8 │             c := d.slot
I see. Thanks for explaining.

2025-02-20 04:40 UTC, OmarTawfik approved these changes

2025-02-20 16:23 UTC, merged