cache CI artifacts + other infra fixes
NomicFoundation/slang pull request #228
Opened 2022-12-14 02:49 UTC by OmarTawfik

This adds a bunch of long-due improvements to our infra:

- Improvements to infra bash scripts:
    - Remove zsh/zshrc hermit workarounds, since we are now using dotfile repositories to load personal configuration.
    - Cleans up the same hermit workarounds in bash, since we now have a single top-level hermit environment.
    - Use relative paths (from repository root) everywhere to make it easier to search+replace values.
- Adds a top-level monorepo `package.json` NPM workspace:
    - Fixes VSCode prettier errors where it cannot find the prettier binary. It is now hoisted to repository root.
    - Fixes auto-formatting of bash files in this repo, as it bit me a few times in CI.
    - Allows us to add other NPM packages (like slang APIs) to the same workspace, enjoying the same config and linting.
    - Upgraded some NPM packages to latest versions, to fix vulnerabilities reported by `npm audit`.
- Adopts the `CI` env var (commonly defined in CI environments like GitHub).
    - We can define it locally to replicate/debug any CI failures locally. For example, `CI=true ./scripts/check.sh`.
    - If this is defined, it will make sure that generated files, lock files, and test snapshots are up to date.
    - Additionally, this enables us to run `lint.sh` to try and fix any local lint errors automatically, unless `CI` is defined.
- Fixed a bug where `codegen_utils` formatters would fail without surfacing the underlying error in the `anyhow::Context`.
- Fixed another bug where tests were not rebuilt incrementally when snapshots change.
- Finally, and most importantly, caches `.hermit` and `code-analysis/target` folders in CI, so that CI jobs are much faster.
    - Caching is also crucial for the next few PRs, which adds compatability checks with `solc`, and we cannot afford to download all binaries every single run.

2022-12-14 03:26 UTC, AntonyBlakey commented on .devcontainer/Dockerfile
> -COPY ./scripts/ /root/
The two .zshrc files should stay, and be copied, so that developers using the devcontainer get hermit accessible on their path.

2022-12-14 03:27 UTC, AntonyBlakey commented on .devcontainer/scripts/.zshrc_devcontainer
> -#!/bin/zsh
The two .zshrc files should stay, and be copied, so that developers using the devcontainer get hermit accessible on their path.

2022-12-14 03:27 UTC, AntonyBlakey commented on .devcontainer/scripts/.zshrc
> -#!/bin/zsh
The two .zshrc files should stay, and be copied, so that developers using the devcontainer get hermit accessible on their path.

2022-12-14 03:38 UTC, AntonyBlakey requested changes
The two .zshrc files should stay, and be copied, so that developers using the devcontainer get hermit accessible on their path.

Doesn't belong in dotfiles because e.g. my dotfiles are used for many contexts, including my host machine, and I don't want to special case them for certain projects. Hence I load .zshrc-devcontainer and presume that will do stuff that is project-specific.

2022-12-14 15:34 UTC, OmarTawfik commented
zsh files change reverted.

2022-12-15 02:10 UTC, AntonyBlakey approved these changes

2022-12-15 04:48 UTC, merged