improve ebnf syntax
NomicFoundation/slang pull request #405
Opened 2023-04-04 16:40 UTC by OmarTawfik

- update ebnf grammar to latest syntax
- fix a bunch of precedence issues when generating sub expressions
- break really long lines (operators, keywords)
- indicate associativity via parenthesis for now

closes #123

2023-04-05 01:18 UTC, AntonyBlakey requested changes
Parens don't work for associativity because either recursive branch could be taken. Comments are the best option.

2023-04-06 01:03 UTC, OmarTawfik commented
f2f: Will remove parens and switch to use comments for now.

2023-04-06 05:48 UTC, OmarTawfik commented on crates/codegen/ebnf/src/serialization.rs
>              EbnfNode::Range { from, to } => {
`[a-z]`

2023-04-06 05:52 UTC, OmarTawfik commented on crates/codegen/ebnf/src/precedence_parser.rs
>          for operator in &self.definition.operators {
f2f: Will remove parens and switch to use comments to indicate associativity.

2023-04-14 02:52 UTC, OmarTawfik commented
Using comments now to indicate associativity.

2023-04-14 09:32 UTC, AntonyBlakey approved these changes

2023-04-14 11:43 UTC, merged