Reinstate `not_followed_by` and add to `DecimalLiteral` also remove `_` in dsl keywords.
NomicFoundation/slang pull request #575
Opened 2023-08-23 09:43 UTC by AntonyBlakey

2023-08-24 08:24 UTC, OmarTawfik requested changes
I suggest checking the other places in the YAML grammar where we are using `notFollowedBy`. For example, I just checked `MultilineComment`, and because the new DSL doesn't use it, we fail to scan `/* foo **/`. I suggest adding a test for that in `crates/solidity/outputs/cargo/tests/src/scanner/mod.rs`.

2023-08-28 09:47 UTC, OmarTawfik approved these changes
Looks great!

2023-08-28 14:43 UTC, Xanewok approved these changes
Left a small suggestion.

2023-08-28 14:43 UTC, Xanewok commented on crates/codegen/parser/runtime/src/support/scanner_macros.rs
>      ($stream:ident, $scanner:expr, $not_followed_by:expr) => {
nit: I like how `delimited by`  tokens improve legibility of the DSL, maybe changing it to
```
($stream:ident, $scanner:expr, not followed by: $not_followed_by:expr)
```

would improve legibility of `scan_not_followed_by` macro calls here?

2023-08-28 14:43 UTC, Xanewok commented on crates/codegen/parser/runtime/src/support/scanner_macros.rs
>  #[allow(unused_macros)]
Is this `allow` still needed?

2023-08-29 11:16 UTC, merged