Minor editing improvements
NomicFoundation/slang pull request #584
Opened 2023-08-30 11:18 UTC by Xanewok

These are small tweaks I found helpful when working on the codebase - I found the template syntax most helpful when working with the code, the rest is very minor but hopefully helpful.

2023-08-31 15:29 UTC, AntonyBlakey requested changes

2023-09-04 21:08 UTC, Xanewok commented on .vscode/extensions.json
>      "rust-lang.rust-analyzer",
Done in 623c5bd50d5881ee321e046f0fa49c81f4fc971d

2023-09-05 09:25 UTC, OmarTawfik approved these changes

2023-09-06 10:17 UTC, AntonyBlakey approved these changes

2023-09-06 10:34 UTC, merged