Specify `Optional(Required(List))` in v2 where we do in v1
NomicFoundation/slang pull request #668
Opened 2023-11-20 18:51 UTC by Xanewok

Part of #652 

Let's unify these definitions to be in line with what's in v0/v1 as to
not change the definition and the CST shape once we switch to using v2
as our source of truth for the parser.

This is independent whether we will want that *eventually* or not. For
now, we should keep things consistent during the migration period. After
that, we can make a decision whether we want to keep these empty nodes
in the CST or not in the absence of any separated items.

2023-11-20 23:47 UTC, OmarTawfik commented on crates/solidity/inputs/language/src/definition.rs
> +                            enabled = From("0.4.22")
looks like a few ones still have `allow_empty = true`. Is this intended?

2023-11-20 23:49 UTC, OmarTawfik requested changes
looks like a few ones still have `allow_empty = true`. Is this intended?

2023-11-21 12:27 UTC, Xanewok commented
The three remaining `allow_empty = true` are separated as a bug-fix in #667 along with regression tests, while the ones changed are are just about not emitting the empty nodes and using the same definition as in v0/v1.

2023-11-21 21:03 UTC, OmarTawfik approved these changes

2023-11-21 22:11 UTC, merged