Refactor `BuiltInLabel` to avoid duplication
NomicFoundation/slang pull request #992
Opened 2024-05-29 14:53 UTC by ggiraldez

Moves the `BuiltInLabel` enum from the parser generator into the language definition and remove duplication in the `kinds` template.

TODO: after applying #976, we need to also remove the `BuiltInLabel` introduced by that PR.
TODO: needs updating after #991 as well to move the `builtin_labels` into the new `KindsModel`.

2024-06-04 10:39 UTC, Xanewok commented
#991 has finally landed; thanks for splitting the work and waiting on it!

2024-06-05 08:21 UTC, Xanewok requested changes
Thanks! I'd like to bundle the kinds together but other than that, looks good to me :+1:

2024-06-05 15:36 UTC, ggiraldez commented on crates/codegen/runtime/cargo/src/runtime/kinds.rs.jinja2
> +    {% for label in model.builtin_labels -%}
Yes, of course, will do.

2024-06-05 15:46 UTC, ggiraldez commented on crates/codegen/runtime/cargo/src/runtime/kinds.rs.jinja2
> +    {% for label in model.builtin_labels -%}
I moved it to the `KindsModel` and implemented `Default` to load the variants. I think this is fine, but we may prefer to have an explicit `for_stubs()`. Or maybe use `derive-new` to provide the default value? I'm wary of adding dependencies for small things like this.

2024-06-05 17:40 UTC, Xanewok commented on crates/codegen/runtime/cargo/src/runtime/kinds.rs.jinja2
> +    {% for label in model.builtin_labels -%}
I think the explicit default is fine for now, thanks!

2024-06-05 17:43 UTC, Xanewok approved these changes
LGTM! Let's merge this once CI is happy (try `scripts/bin/infra ci`)

2024-06-05 17:45 UTC, ggiraldez commented
> LGTM! Let's merge this once CI is happy (try `scripts/bin/infra ci`)

Yes, I usually run that before each push... except when I forget :facepalm: Thanks!

2024-06-05 18:29 UTC, merged